### ISSUE TITLE
Missing empty_world.xml

### ISSUE THREAD

**Issue by balandbal** [ubi-agni/mujoco_ros_pkgs#1]
Missing empty_world.xml
===

The [mujoco/test/empty_world.xml](https://github.com/DavidPL1/mujoco_ros_pkgs/tree/noetic-devel/mujoco_ros) model file is not present and is breaking [mujoco_ros/demo.launch](https://github.com/DavidPL1/mujoco_ros_pkgs/blob/noetic-devel/mujoco_ros/launch/demo.launch).

**Comment by DavidPL1** [comment]
This has already been fixed in the parallel-data feature branch by 4db98a20. The commit is now also cherry-picked into noetic-devel.
