### ISSUE TITLE
How to Add RGB-D + Segmentation Image Camera Streams in Simulation?

### ISSUE THREAD

**Issue by Ekanshh** [ubi-agni/mujoco_ros_pkgs#35]
Hi,

I’m interested to know how to add RGB-D + segmentation image camera streams to my simulation. I came across [this discussion](https://github.com/google-deepmind/mujoco/discussions/990#discussioncomment-6577271) by @DavidPL1 featuring the following image and I'd like to reproduce similar results:

![image](https://github.com/user-attachments/assets/8f0c58b6-043a-4c28-b782-9fa3f04c2e9f)

Could you kindly assist with the following?
1. Defining and configuring an RGBD camera in XML/URDF.
2. Enabling depth sensing and image segmentation.
3. Any relevant resources or examples.

Thanks in advance for your help!

**Comment by DavidPL1** [comment]
Please have a look here: https://github.com/ubi-agni/mujoco_ros_pkgs/blob/noetic-devel/mujoco_ros/README.md#camera-streams

If you need more help, I can assist you with more details starting next tuesday.

**Comment by Ekanshh** [comment]
Thank you for your guidance @DavidPL1! I successfully reproduced the results, and here’s my outcome:

![image](https://github.com/user-attachments/assets/4c5795a3-09d9-4037-a0e9-f33402be99a3)

Great work on this project! :100:
