### ISSUE TITLE
Issue:  Incorrect Quaternion Indexing in Pose Extraction in `get_body_state` Service Callback

### ISSUE THREAD

**Issue by Ekanshh** [ubi-agni/mujoco_ros_pkgs#36]
Quaternion indexing in the pose extraction within the get_body_state service callback uses an incorrect multiplier for xquat, resulting in inaccurate orientation data for the requested body: [L416-L420](https://github.com/ubi-agni/mujoco_ros_pkgs/blob/c4355cad5b38e823da25f481ada7ab4e51443aeb/mujoco_ros/src/callbacks.cpp#L416C3-L420C1)

**Current Code** (incorrect, uses `3` as multiplier): 

```cpp
resp.state.pose.pose.orientation.w = data_->xquat[body_id * 3];
resp.state.pose.pose.orientation.x = data_->xquat[body_id * 3 + 1];
resp.state.pose.pose.orientation.y = data_->xquat[body_id * 3 + 2];
resp.state.pose.pose.orientation.z = data_->xquat[body_id * 3 + 3];
```

**Proposed Fix**: Use `4` as multiplier for proper quaternion indexing:
```cpp
resp.state.pose.pose.orientation.w = data_->xquat[body_id * 4];
resp.state.pose.pose.orientation.x = data_->xquat[body_id * 4 + 1];
resp.state.pose.pose.orientation.y = data_->xquat[body_id * 4 + 2];
resp.state.pose.pose.orientation.z = data_->xquat[body_id * 4 + 3];
```

**Comment by DavidPL1** [comment]
Thanks for pointing it out. Next time feel free to open a PR :)
